name: LandRaisers
version: '${project.version}'
main: me.marko.landraisers.LandRaisers
api-version: '1.20'
commands:
  plotTest:
    description: claimPlots
    usage: /plotTest [subcommand]
    aliases: ["plotClaim", "pc"]
  crateTest:
    description: yeah
    usage: /crateTest
